---
abstract: 'Tags helper for stars evaluation.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.03
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-HTML-Stars
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.02
  Error::Pure: 0.07
  List::Util: 0
  MIME::Base64: 0
  Readonly: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tags-HTML-Stars
  homepage: https://github.com/michal-josef-spacek/Tags-HTML-Stars
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-HTML-Stars
version: '0.02'
